title: Brian Valachovic - Product Leader - Product Manaagement & Design, UX Research & Design, UI Design & Development
description: Professional Product Leadership - almost 30 years of experience in software & digital product design & development

collections:
  case_studies:
    output: true
    permalink: /case-studies/:name/